CREATE TABLE IF NOT EXISTS Users(
UserID TEXT PRIMARY KEY,
Name TEXT,
Email TEXT,
Gender TEXT,
DateOfBirth DATE,
YearOfRegistration INTEGER,
ActiveUser INTEGER
);

CREATE TABLE IF NOT EXISTS Phasebook(
UserID PRIMARY KEY,
Friends INTEGER,
DateLogin DATE,
FOREIGN KEY(UserID) REFERENCES Users(UserID)
);

CREATE TABLE IF NOT EXISTS Viewtube(
UserID PRIMARY KEY,
Subscribers INTEGER,
DateLogin DATE,
FOREIGN KEY(UserID) REFERENCES Users(UserID)
);

CREATE TABLE IF NOT EXISTS Whatsup(
UserID PRIMARY KEY,
Contacts INTEGER,
DateLogin DATE,
FOREIGN KEY(UserID) REFERENCES Users(UserID)
);